#pragma once

#include "aria/internal/types.hpp"
#include "aria/internal/compiler/core/string_view.hpp"

#include <variant>

namespace Aria::Internal {

    struct TypeInfo;

    #define TYPED_OP(name) \
        name##I8, \
        name##I16, \
        name##I32, \
        name##I64, \
        name##U8, \
        name##U16, \
        name##U32, \
        name##U64, \
        name##F32, \
        name##F64,

    #define INTEGRAL_OP(name) \
        name##I8, \
        name##I16, \
        name##I32, \
        name##I64, \
        name##U8, \
        name##U16, \
        name##U32, \
        name##U64,

    // A struct used to reference some memory at runtime
    // This memory could be a stack slot, global variable or pointer
    struct MemRef {
    private:
        struct StackSlotRef {
            i32 Slot = 0;
            size_t Size = 0;
            size_t Offset = 0;
        };

    public:
        MemRef() {}
        explicit MemRef(i32 stackSlot, size_t size, size_t offset = 0) : m_Data(StackSlotRef(stackSlot, size, offset)) {}
        explicit MemRef(const std::string& global) : m_Data(global) {}
        explicit MemRef(void* ptr) : m_Data(ptr) {}

        bool ContainsStackSlot() const { return std::get_if<StackSlotRef>(&m_Data) != nullptr; }
        StackSlotRef GetStackSlot() const { return std::get<StackSlotRef>(m_Data); }

        bool ContainsGlobal() const { return std::get_if<std::string>(&m_Data) != nullptr; }
        std::string& GetGlobal() { return std::get<std::string>(m_Data); }
        const std::string& GetGlobal() const { return std::get<std::string>(m_Data); }

        bool ContainsPointer() const { return std::get_if<void*>(&m_Data) != nullptr; }
        void* GetPointer() { return std::get<void*>(m_Data); }
        const void* GetPointer() const { return std::get<void*>(m_Data); }

    private:
        std::variant<StackSlotRef, std::string, void*> m_Data;
    };

    enum class OpCodeType {
        Nop,

        Alloca,
        Copy,
        Dup,

        PushSF,
        PopSF,

        LoadI8,
        LoadI16,
        LoadI32,
        LoadI64,
        LoadU8,
        LoadU16,
        LoadU32,
        LoadU64,
        LoadF32,
        LoadF64,
        LoadStr,

        SetGlobal,
        Function,
        Label,
        Jmp,
        Jt,
        Jf,

        Call,
        CallExtern,
        Ret,

        TYPED_OP(Negate)

        TYPED_OP(Add)
        TYPED_OP(Sub)
        TYPED_OP(Mul)
        TYPED_OP(Div)
        TYPED_OP(Mod)

        INTEGRAL_OP(And)
        INTEGRAL_OP(Or)
        INTEGRAL_OP(Xor)

        TYPED_OP(Cmp)
        TYPED_OP(Ncmp)
        TYPED_OP(Lt)
        TYPED_OP(Lte)
        TYPED_OP(Gt)
        TYPED_OP(Gte)

        // NOTE: These were generated by macros and then inlined
        CastI8ToI8,
        CastI8ToI16,
        CastI8ToI32,
        CastI8ToI64,
        CastI8ToU8,
        CastI8ToU16,
        CastI8ToU32,
        CastI8ToU64,
        CastI8ToF32,
        CastI8ToF64,

        CastI16ToI8,
        CastI16ToI16,
        CastI16ToI32,
        CastI16ToI64,
        CastI16ToU8,
        CastI16ToU16,
        CastI16ToU32,
        CastI16ToU64, 
        CastI16ToF32, 
        CastI16ToF64, 

        CastI32ToI8,
        CastI32ToI16,
        CastI32ToI32,
        CastI32ToI64,
        CastI32ToU8,
        CastI32ToU16,
        CastI32ToU32,
        CastI32ToU64, 
        CastI32ToF32, 
        CastI32ToF64, 

        CastI64ToI8,
        CastI64ToI16,
        CastI64ToI32,
        CastI64ToI64,
        CastI64ToU8,
        CastI64ToU16,
        CastI64ToU32,
        CastI64ToU64,
        CastI64ToF32,
        CastI64ToF64,

        CastU8ToI8,
        CastU8ToI16,
        CastU8ToI32,
        CastU8ToI64,
        CastU8ToU8,
        CastU8ToU16,
        CastU8ToU32,
        CastU8ToU64,
        CastU8ToF32,
        CastU8ToF64,

        CastU16ToI8,
        CastU16ToI16,
        CastU16ToI32,
        CastU16ToI64,
        CastU16ToU8,
        CastU16ToU16,
        CastU16ToU32,
        CastU16ToU64,
        CastU16ToF32,
        CastU16ToF64,

        CastU32ToI8,
        CastU32ToI16,
        CastU32ToI32,
        CastU32ToI64,
        CastU32ToU8,
        CastU32ToU16,
        CastU32ToU32,
        CastU32ToU64,
        CastU32ToF32,
        CastU32ToF64,

        CastU64ToI8,
        CastU64ToI16,
        CastU64ToI32,
        CastU64ToI64,
        CastU64ToU8,
        CastU64ToU16,
        CastU64ToU32,
        CastU64ToU64,
        CastU64ToF32,
        CastU64ToF64,

        CastF32ToI8,
        CastF32ToI16,
        CastF32ToI32,
        CastF32ToI64,
        CastF32ToU8,
        CastF32ToU16,
        CastF32ToU32,
        CastF32ToU64,
        CastF32ToF32,
        CastF32ToF64,

        CastF64ToI8,
        CastF64ToI16,
        CastF64ToI32,
        CastF64ToI64,
        CastF64ToU8,
        CastF64ToU16,
        CastF64ToU32,
        CastF64ToU64,
        CastF64ToF32,
        CastF64ToF64,
    };

    #undef TYPED_OP

    struct OpCodeAlloca {
        size_t Size = 0;
        TypeInfo* ResolvedType = nullptr;
    };

    struct OpCodeCopy {
        MemRef DstMem{};
        MemRef SrcMem{};
    };

    struct OpCodeLoad {
        std::variant<i8, u8, i16, u16, i32, u32, i64, u64, f32, f64, StringView> Data;
        TypeInfo* ResolvedType = nullptr;
    };

    struct OpCodeSetGlobal {
        std::string Name;
        MemRef Mem;
    };

    struct OpCodeConditionalJump {
        MemRef Mem{};
        std::string Label;
    };

    struct OpCodeMath {
        MemRef LHSMem{};
        MemRef RHSMem{};

        TypeInfo* ResolvedType = nullptr;
    };

    struct OpCodeCast {
        MemRef Mem{};
        TypeInfo* ResolvedType = nullptr;
    };

    struct OpCode {
        OpCodeType Type = OpCodeType::Nop;
        std::variant<MemRef, std::string, OpCodeAlloca, OpCodeCopy, OpCodeLoad, OpCodeSetGlobal, OpCodeConditionalJump, OpCodeMath, OpCodeCast> Data;
        std::string DebugData; // Optional debug data the compiler can provide
    };

} // namespace Aria::Internal
